name: resto_app_v3
description: Submission 3 Flutter Fundamental; Resto App Favorite
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.2.0
  http: ^0.13.4
  provider: ^6.0.3
  intl: ^0.17.0
  android_alarm_manager_plus: ^2.0.5
  flutter_local_notifications: ^9.6.0
  rxdart: ^0.27.4
  sqflite: ^2.0.2+1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  mockito: ^5.2.0
  build_runner: ^2.1.11


flutter:
  uses-material-design: true
  assets:
    - images/restaurant.png